import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Sidebar from "./student/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Student Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className={`absolute left-[20%] w-[80%] h-screen max-h-screen flex`}>
          <Sidebar />
          <section className="w-full h-screen">
            {children}
          </section>
        </main>
      </body>
    </html>
  );
}
